# Generated by Django 5.1.2 on 2024-12-12 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('startdatetime', models.DateTimeField(blank=True, null=True)),
                ('enddatetime', models.DateTimeField(blank=True, null=True)),
                ('locationType', models.CharField(choices=[('0', 'No location'), ('1', 'QR Code scan'), ('2', 'GPS location')], default='0', max_length=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
        ),
    ]
